Added sending report to specified email

diff --git a/memory_check b/memory_check
--- a/memory_check
+++ b/memory_check
@@ -11,7 +11,7 @@ while getopts ":c:w:e:" OPTIONS; do
 done
 
 # check options if it exists, is valid and critical threshold greater than warning threshold
-if [ -z "$CRITICAL" ] || ! [[ "$CRITICAL" =~ ^[0-9]+$ ]] || [ -z "$WARNING" ] || ! [[ "$WARNING" =~ ^[0-9]+$ ]] || [ -z "$EMAIL" ] || ! [[ "$EMAIL" =~ ^[A-Za-z].*@[A-Za-z0-9].* ]] || [ "$CRITICAL" -le "$WARNING" ] || [ "$CRITICAL" -gt 100 ] || [ "$WARNING" -eq 0 ]; then
+if [ -z "$CRITICAL" ] || ! [[ "$CRITICAL" =~ ^[0-9]+$ ]] || [ "$CRITICAL" -gt 100 ]  || [ -z "$WARNING" ] || ! [[ "$WARNING" =~ ^[0-9]+$ ]] || [ "$WARNING" -eq 0 ] || [ -z "$EMAIL" ] || ! [[ "$EMAIL" =~ ^[A-Za-z].*@[A-Za-z0-9].* ]] || [ "$CRITICAL" -le "$WARNING" ]; then
 	printf "ERROR: memory_check [-c <percentage>] [-w <percentage>] [-e <email>]
 Parameters are required and non-positional.
 	-c <percentage>		Critical threshold.
@@ -20,24 +20,23 @@ Parameters are required and non-positional.
 	-w <percentage>		Warning threshold.
 				Value must be at least greater than 0.
 	-e <email>		Email address to send the report.\n"
-	exit 3		# exit code for invalid input
+	exit 3													# exit code for invalid input
 else
 	TOTAL_MEMORY=$( free | grep Mem: | awk '{ print $2 }' )
 	USED_MEMORY=$( free | grep Mem: | awk '{ print $3 }' )
-	TOP_PROCESS=$( ps axo pid,comm,rss,%mem --sort -rss | head -n 11 )	# top 10 processes using the most memory
+	TOP_PROCESSES=$( ps axo pid,comm,rss,%mem --sort -rss | head -n 11 )	# top 10 processes using the most memory based on rss
 	CURRENT_TIME=$( date +%Y%m%d\ %H:%M )
 
-	CHECK_CRITICAL=$(($CRITICAL*$TOTAL_MEMORY/100))		# critical threshold
-	CHECK_WARNING=$(($WARNING*$TOTAL_MEMORY/100))		# warning threshold
+	CHECK_CRITICAL=$(($CRITICAL*$TOTAL_MEMORY/100))			# critical threshold
+	CHECK_WARNING=$(($WARNING*$TOTAL_MEMORY/100))			# warning threshold
 
 	# checking
-	if [ "$CRITICAL" -le "$USED_MEMORY" ]; then
-		echo $CURRENT_TIME "memory check - critical"
-		echo "$TOP_PROCESS"
-		exit 2		# exit code if 
-	elif [ "$WARNING" -le "$USED_MEMORY" ]; then
-		exit 1
+	if [ "$CHECK_CRITICAL" -le "$USED_MEMORY" ]; then
+		echo "$TOP_PROCESSES" | mail -s "$CURRENT_TIME memory check - critical" $EMAIL
+		exit 2												# exit code if used memory is greater than or equal to critical threshold
+	elif [ "$CHECK_WARNING" -le "$USED_MEMORY" ]; then
+		exit 1												# exit code if used memory is greater than or equal to warning threshold but less than the critical threshold
 	else
-		exit 0
+		exit 0												# exit code if used memory is less than warning threshold
 	fi
 fi
